### ISSUE TITLE
Add TOML Configuration Support for Pattern Levels

### ISSUE THREAD

**Issue by D-Gaspa** [D-Gaspa/structlog_config#3]
Add support for pattern-based logger levels in TOML configuration files.

Tasks:
- Add new section in TOML for pattern levels
- Parse and validate pattern configurations
- Handle multiple patterns with proper ordering
- Maintain backward compatibility
- Update configuration documentation

Example TOML:
```toml
[logging]
level = "INFO"

[logging.patterns]
"sqlalchemy.*" = "WARNING"
"sqlalchemy.engine.*" = "ERROR"
```

Acceptance Criteria:
- TOML configuration correctly parsed
- Invalid configurations raise appropriate errors
- Existing configurations continue to work
- Documentation updated with new options
